# Generated by Django 4.0.1 on 2022-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('player_number', models.IntegerField(null=True)),
                ('class_standing', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('major', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('GOAL', 'Goalkeeper'), ('FOGO', 'Faceoff Specialist'), ('LSM', 'Long-Stick Midfielder'), ('SSDM', 'Short-Stick Defensive Midfielder')], default='ATT', max_length=4)),
                ('hometown', models.CharField(max_length=50)),
                ('height_feet', models.IntegerField(null=True)),
                ('height_inches', models.IntegerField(null=True)),
                ('weight_pounds', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
