# Generated by Django 4.0.1 on 2022-01-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roster_coach_roster_loss_count_roster_player_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Scorebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='class_standing',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height_feet',
            field=models.IntegerField(null=True, verbose_name='Height (feet)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height_inches',
            field=models.IntegerField(null=True, verbose_name='Height (inches)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='hometown',
            field=models.CharField(max_length=50, verbose_name='Hometown'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='major',
            field=models.CharField(max_length=100, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(null=True, verbose_name='Uniform Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('G', 'Goalkeeper'), ('FOGO', 'Faceoff Specialist'), ('LSM', 'Long-Stick Midfielder'), ('SSDM', 'Short-Stick Defensive Midfielder')], default='ATT', max_length=4, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_pounds',
            field=models.IntegerField(null=True, verbose_name='Weight (pounds)'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='coach',
            field=models.CharField(default='', max_length=100),
        ),
    ]
