# Generated by Django 4.0.1 on 2022-01-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='coach',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roster',
            name='loss_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='player_list',
            field=models.ManyToManyField(to='api.Player', verbose_name='List of Players'),
        ),
        migrations.AddField(
            model_name='roster',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roster',
            name='team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roster',
            name='win_count',
            field=models.IntegerField(default=0),
        ),
    ]
