# Generated by Django 4.0.1 on 2022-01-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_class_standing_player_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='class_standing',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('GOAL', 'Goalkeeper'), ('FOGO', 'Faceoff Specialist'), ('LSM', 'Long-Stick Midfielder'), ('SSDM', 'Short-Stick Defensive Midfielder')], default='ATT', max_length=4),
        ),
    ]
